#! /bin/bash

handle() { echo "dnsmasq/run: got signal"; exit; }
trap handle SIGINT

[[ -e /usr/local/vamp/good2go ]] || exit 1

if [[ -z $VAMP_VGA_DNS_ENABLE ]] ; then
  echo "dnsmasq/run: disabling"
  sv stop dnsmasq
  exit
fi

: "${VAMP_VGA_CONF_DIR:=/usr/local/vamp}"
: "${VAMP_VGA_DNS_PORT:=5353}"

# Add virtual hosts to /etc/hosts and reload dnsmasq
if [[ -n $VAMP_VGA_DNS_ENABLE ]]; then
  # Overwrite default port of 5353, if specified
  if [[ -n $VAMP_VGA_DNS_PORT && $VAMP_VGA_DNS_PORT =~ ^-?[0-9]+$ ]]; then
    echo "port=${VAMP_VGA_DNS_PORT}" > /etc/dnsmasq.conf
  fi

  awk -v host="$( hostname -i )" \
    'BEGIN { print "127.0.0.1\tlocalhost\n::1\tlocalhost\n" };
    /^  acl .* hdr\(host\) -i .*$/ { print host "\t" $NF }' "${configuration}" > /etc/hosts

  kill -s SIGHUP $( pidof dnsmasq ) || dnsmasq
fi
