#! /bin/bash

# Attempt to reload HAproxy if it's not running

handle() { echo "haproxy/run: got signal"; exit; }
trap handle SIGINT

[[ -e /usr/local/vamp/haproxy.cfg ]] || exit 1

pidof haproxy &> /dev/null || /usr/local/vamp/haproxy-reload.sh
