#! /bin/bash

handle() { echo "confd/run: got signal"; exit; }
trap handle SIGINT

[[ -e /usr/local/vamp/good2go ]] || exit 1

: "${VAMP_GATEWAY_AGENT_CONFD_LOGLEVEL:=warn}"

if [ -e /usr/local/vamp/token ]; then
  VAMP_KEY_VALUE_STORE_TOKEN="$( cat /usr/local/vamp/token )"
fi

exec 2>&1

if [[ -z ${VAMP_KEY_VALUE_STORE_TOKEN} ]] ; then
  exec /usr/bin/confd \
     -backend ${VAMP_KEY_VALUE_STORE_TYPE} \
     -node ${VAMP_KEY_VALUE_STORE_CONNECTION} \
     -log-level="$VAMP_GATEWAY_AGENT_CONFD_LOGLEVEL" \
     -onetime=true
else
  exec /usr/bin/confd \
     -backend ${VAMP_KEY_VALUE_STORE_TYPE} \
     -node ${VAMP_KEY_VALUE_STORE_CONNECTION} \
     -auth-type token -auth-token ${VAMP_KEY_VALUE_STORE_TOKEN} \
     -log-level="$VAMP_GATEWAY_AGENT_CONFD_LOGLEVEL" \
     -onetime=true
fi
